-- ============================================================================
-- FIX BIRTHDAY VIEWS TO USE MEMBERS_CONSOLIDATED
-- ============================================================================
-- Problem: Birthday views are querying from 'members' table which is empty
-- Solution: Recreate views to query from 'members_consolidated' table
-- ============================================================================

BEGIN;

-- Drop existing views
DROP VIEW IF EXISTS vw_todays_birthdays CASCADE;
DROP VIEW IF EXISTS vw_upcoming_birthdays CASCADE;

-- ============================================================================
-- VIEW: Today's Birthdays (from members_consolidated)
-- ============================================================================
CREATE OR REPLACE VIEW vw_todays_birthdays AS
SELECT
    m.member_id,
    COALESCE(m.membership_number, 'MEM' || LPAD(m.member_id::TEXT, 6, '0')) as membership_number,
    m.firstname AS first_name,
    m.surname AS last_name,
    m.id_number,
    m.date_of_birth,
    m.email,
    m.cell_number AS phone_number,
    m.ward_code,
    COALESCE(w.ward_name, 'Ward ' || m.ward_code) AS ward_name,
    m.municipality_name,
    m.district_code,
    m.district_name,
    m.province_code,
    m.province_name,
    COALESCE(mst.status_name, 'Active') AS membership_status,
    m.date_joined AS membership_start_date,
    m.expiry_date AS membership_expiry_date,
    m.language_id,
    COALESCE(l.language_name, 'English') AS language_name,
    COALESCE(l.language_code, 'en') AS language_code,
    EXTRACT(YEAR FROM AGE(CURRENT_DATE, m.date_of_birth))::INTEGER AS age,

    -- Language selection logic
    CASE
        WHEN m.province_code = 'GP' THEN 2  -- Gauteng defaults to English
        WHEN m.language_id IS NOT NULL THEN m.language_id
        ELSE 2  -- Default to English
    END AS selected_language_id,

    CASE
        WHEN m.province_code = 'GP' THEN 'English'
        WHEN l.language_name IS NOT NULL THEN l.language_name
        ELSE 'English'
    END AS selected_language_name,

    CASE
        WHEN m.province_code = 'GP' THEN 'en'
        WHEN l.language_code IS NOT NULL THEN l.language_code
        ELSE 'en'
    END AS selected_language_code,

    -- Birthday message (will be generated by service)
    COALESCE(
        (
            SELECT REPLACE(bmt.message_template, '{firstname}', m.firstname)
            FROM birthday_message_templates bmt
            WHERE bmt.language_id = CASE
                WHEN m.province_code = 'GP' THEN 2
                WHEN m.language_id IS NOT NULL THEN m.language_id
                ELSE 2
            END
            AND bmt.is_active = true
            LIMIT 1
        ),
        REPLACE('Happy Birthday {firstname}! The EFF wishes you a wonderful day filled with joy and prosperity. Thank you for being a valued member. Aluta Continua!', '{firstname}', m.firstname)
    ) AS birthday_message,

    CASE
        WHEN m.province_code = 'GP' THEN 'Gauteng - English'
        WHEN m.language_id IS NOT NULL THEN 'Member Preference'
        ELSE 'Default - English'
    END AS language_selection_reason,

    -- Check if message already sent today
    CASE
        WHEN EXISTS (
            SELECT 1 FROM birthday_messages_sent bms
            WHERE bms.member_id = m.member_id
            AND DATE(bms.sent_at) = CURRENT_DATE
        ) THEN true
        ELSE false
    END AS message_sent_today

FROM members_consolidated m
LEFT JOIN wards w ON m.ward_code = w.ward_code
LEFT JOIN languages l ON m.language_id = l.language_id
LEFT JOIN membership_statuses mst ON m.membership_status_id = mst.status_id
WHERE
    -- Birthday is today
    EXTRACT(MONTH FROM m.date_of_birth) = EXTRACT(MONTH FROM CURRENT_DATE)
    AND EXTRACT(DAY FROM m.date_of_birth) = EXTRACT(DAY FROM CURRENT_DATE)
    -- Has valid phone number
    AND m.cell_number IS NOT NULL
    AND m.cell_number != ''
    AND LENGTH(TRIM(m.cell_number)) >= 10
ORDER BY m.firstname, m.surname;

-- ============================================================================
-- VIEW: Upcoming Birthdays (next 7 days from members_consolidated)
-- ============================================================================
CREATE OR REPLACE VIEW vw_upcoming_birthdays AS
SELECT
    m.member_id,
    COALESCE(m.membership_number, 'MEM' || LPAD(m.member_id::TEXT, 6, '0')) as membership_number,
    m.firstname AS first_name,
    m.surname AS last_name,
    m.cell_number AS phone_number,
    m.date_of_birth,
    EXTRACT(YEAR FROM AGE(CURRENT_DATE, m.date_of_birth))::INTEGER AS current_age,
    m.language_id,
    COALESCE(l.language_name, 'English') AS language_name,
    COALESCE(l.language_code, 'en') AS language_code,

    -- Calculate days until birthday
    CASE
        WHEN EXTRACT(MONTH FROM m.date_of_birth) = EXTRACT(MONTH FROM CURRENT_DATE)
             AND EXTRACT(DAY FROM m.date_of_birth) >= EXTRACT(DAY FROM CURRENT_DATE)
        THEN EXTRACT(DAY FROM m.date_of_birth) - EXTRACT(DAY FROM CURRENT_DATE)

        WHEN EXTRACT(MONTH FROM m.date_of_birth) > EXTRACT(MONTH FROM CURRENT_DATE)
        THEN (
            (EXTRACT(YEAR FROM CURRENT_DATE) || '-' || EXTRACT(MONTH FROM m.date_of_birth) || '-' || EXTRACT(DAY FROM m.date_of_birth))::DATE
            - CURRENT_DATE
        )

        ELSE (
            ((EXTRACT(YEAR FROM CURRENT_DATE) + 1) || '-' || EXTRACT(MONTH FROM m.date_of_birth) || '-' || EXTRACT(DAY FROM m.date_of_birth))::DATE
            - CURRENT_DATE
        )
    END AS days_until_birthday,

    m.province_name,
    m.province_code,
    m.district_name,
    m.municipality_name,

    CASE
        WHEN m.province_code = 'GP' THEN 'English'
        WHEN l.language_name IS NOT NULL THEN l.language_name
        ELSE 'English'
    END AS selected_language

FROM members_consolidated m
LEFT JOIN languages l ON m.language_id = l.language_id
WHERE
    -- Has valid phone number
    m.cell_number IS NOT NULL
    AND m.cell_number != ''
    AND LENGTH(TRIM(m.cell_number)) >= 10
    -- Birthday is in the next 7 days
    AND (
        (EXTRACT(MONTH FROM m.date_of_birth) = EXTRACT(MONTH FROM CURRENT_DATE)
         AND EXTRACT(DAY FROM m.date_of_birth) >= EXTRACT(DAY FROM CURRENT_DATE))
        OR
        (EXTRACT(MONTH FROM m.date_of_birth) = EXTRACT(MONTH FROM CURRENT_DATE + INTERVAL '7 days')
         AND EXTRACT(DAY FROM m.date_of_birth) <= EXTRACT(DAY FROM CURRENT_DATE + INTERVAL '7 days'))
    )
ORDER BY days_until_birthday, m.firstname;

COMMIT;

-- Verify the fix
SELECT 'vw_todays_birthdays' as view_name, COUNT(*) as record_count FROM vw_todays_birthdays
UNION ALL
SELECT 'vw_upcoming_birthdays' as view_name, COUNT(*) as record_count FROM vw_upcoming_birthdays;

-- Display success message
DO $$
BEGIN
  RAISE NOTICE '✅ Birthday views fixed successfully!';
  RAISE NOTICE '   - vw_todays_birthdays now queries members_consolidated';
  RAISE NOTICE '   - vw_upcoming_birthdays now queries members_consolidated';
END $$;

