import React, { useState } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  MenuItem,
  Grid,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Chip,
  IconButton,
  Alert,
  FormControlLabel,
  Checkbox,
  InputAdornment,
  CircularProgress,
} from '@mui/material';
import { Add as AddIcon, Edit as EditIcon, CheckCircle, Cancel, Delete as DeleteIcon, CloudUpload as CloudUploadIcon, Download as DownloadIcon, Search as SearchIcon, HowToReg as HowToRegIcon } from '@mui/icons-material';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { wardAuditApi } from '../../services/wardAuditApi';

interface WardMeetingManagementProps {
  wardCode: string;
  wardName: string;
  provinceCode: string;
}

interface MeetingFormData {
  meeting_id?: number; // Optional - will be auto-generated by backend
  meeting_type: 'BPA' | 'BGA';
  meeting_date: string;
  presiding_officer_name: string;
  secretary_name: string;
  quorum_required: number;
  quorum_achieved: number;
  total_attendees: number;
  meeting_outcome: string;
  nominated_councillor_id?: number;
  nominated_councillor_name?: string;

  quorum_verified_manually: boolean;
  quorum_verification_notes: string;
  meeting_took_place_verified: boolean;
  meeting_verification_notes: string;
}

const WardMeetingManagement: React.FC<WardMeetingManagementProps> = ({ wardCode, wardName, provinceCode }) => {
  const queryClient = useQueryClient();
  const [openDialog, setOpenDialog] = useState(false);
  const [deleteConfirmOpen, setDeleteConfirmOpen] = useState(false);
  const [recordToDelete, setRecordToDelete] = useState<number | null>(null);

  // Nominate Councillor modal state
  const [nominateCouncillorOpen, setNominateCouncillorOpen] = useState(false);
  const [councillorSearch, setCouncillorSearch] = useState('');
  const [councillorSearchResults, setCouncillorSearchResults] = useState<any[]>([]);
  const [councillorSearchLoading, setCouncillorSearchLoading] = useState(false);
  const [selectedCouncillor, setSelectedCouncillor] = useState<any | null>(null);

  const [formData, setFormData] = useState<MeetingFormData>({
    // meeting_id removed - will be auto-generated by backend
    meeting_type: 'BPA',
    meeting_date: '',
    presiding_officer_name: '',
    secretary_name: '',
    quorum_required: 0,
    quorum_achieved: 0,
    total_attendees: 0,
    meeting_outcome: '',
    nominated_councillor_id: undefined,
    nominated_councillor_name: undefined,

    quorum_verified_manually: false,
    quorum_verification_notes: '',
    meeting_took_place_verified: false,
    meeting_verification_notes: '',
  });

  const [meetingPackageFile, setMeetingPackageFile] = useState<File | null>(null);

  // Fetch ward meetings
  const { data: meetings = [], isLoading } = useQuery({
    queryKey: ['ward-meetings', wardCode],
    queryFn: () => wardAuditApi.getWardMeetings(wardCode),
  });

  // Fetch ward member count
  const { data: wardMemberCount = 0 } = useQuery({
    queryKey: ['ward-member-count', wardCode],
    queryFn: async () => {
      const compliance = await wardAuditApi.getWardCompliance(wardCode);
      return compliance.total_members || 0;
    },
    enabled: !!wardCode,
    staleTime: 60000, // Cache for 1 minute
  });

  // Create meeting mutation
  const createMeetingMutation = useMutation({
    mutationFn: (data: MeetingFormData) =>
      wardAuditApi.createMeetingRecord(wardCode, data, meetingPackageFile || undefined),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ward-meetings', wardCode] });
      queryClient.invalidateQueries({ queryKey: ['ward-compliance-details', wardCode] });
      setOpenDialog(false);
      resetForm();
    },
  });

  // Delete meeting mutation
  const deleteMeetingMutation = useMutation({
    mutationFn: (recordId: number) => wardAuditApi.deleteMeetingRecord(recordId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ward-meetings', wardCode] });
      queryClient.invalidateQueries({ queryKey: ['ward-compliance-details', wardCode] });
      setDeleteConfirmOpen(false);
      setRecordToDelete(null);
    },
  });

  const resetForm = () => {
    setFormData({
      // meeting_id removed - will be auto-generated by backend
      meeting_type: 'BPA',
      meeting_date: '',
      presiding_officer_name: '',
      secretary_name: '',
      quorum_required: 0,
      quorum_achieved: 0,
      total_attendees: 0,
      meeting_outcome: '',
      nominated_councillor_id: undefined,
      nominated_councillor_name: undefined,

      quorum_verified_manually: false,
      quorum_verification_notes: '',
      meeting_took_place_verified: false,
      meeting_verification_notes: '',
    });
    setMeetingPackageFile(null);
    setSelectedCouncillor(null);
    setCouncillorSearch('');
    setCouncillorSearchResults([]);
  };

  // Search for councillors by ID or name
  const handleCouncillorSearch = async (term: string) => {
    setCouncillorSearch(term);
    if (!term.trim() || term.trim().length < 2) {
      setCouncillorSearchResults([]);
      return;
    }
    setCouncillorSearchLoading(true);
    try {
      const results = await wardAuditApi.searchMembersByWard(wardCode, term);
      setCouncillorSearchResults(results);
    } catch {
      setCouncillorSearchResults([]);
    } finally {
      setCouncillorSearchLoading(false);
    }
  };

  const handleSelectCouncillor = (member: any) => {
    setSelectedCouncillor(member);
    setNominateCouncillorOpen(false);
    setFormData(prev => ({
      ...prev,
      nominated_councillor_id: member.member_id || member.id,
      nominated_councillor_name: member.full_name || member.name,
    }));
  };

  const handleSubmit = () => {
    createMeetingMutation.mutate({
      ...formData,
      quorum_achieved: formData.total_attendees,
    });
  };

  const handleChange = (field: keyof MeetingFormData, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleDeleteClick = (recordId: number) => {
    setRecordToDelete(recordId);
    setDeleteConfirmOpen(true);
  };

  const handleDeleteConfirm = () => {
    if (recordToDelete !== null) {
      deleteMeetingMutation.mutate(recordToDelete);
    }
  };

  const handleDeleteCancel = () => {
    setDeleteConfirmOpen(false);
    setRecordToDelete(null);
  };

  // const quorumMet = formData.quorum_achieved >= formData.quorum_required;

  return (
    <Box>
      <Card>
        <CardContent>
          <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
            <Typography variant="h6">
              Ward Meeting Records - {wardName}
            </Typography>
            <Button
              variant="contained"
              startIcon={<AddIcon />}
              onClick={() => setOpenDialog(true)}
            >
              Record New Meeting
            </Button>
          </Box>

          {isLoading ? (
            <Typography>Loading meetings...</Typography>
          ) : meetings.length === 0 ? (
            <Alert severity="info">
              No meeting records found. Click "Record New Meeting" to add the first meeting.
            </Alert>
          ) : (
            <TableContainer component={Paper}>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Date</TableCell>
                    <TableCell>Type</TableCell>
                    <TableCell>Presiding Officer</TableCell>
                    <TableCell>Quorum</TableCell>
                    <TableCell>Attendees</TableCell>
                    <TableCell>Package</TableCell>
                    <TableCell>Outcome / Councillor</TableCell>
                    <TableCell>Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {meetings.map((meeting: any) => (
                    <TableRow key={meeting.record_id}>
                      <TableCell>
                        {new Date(meeting.created_at).toLocaleDateString()}
                      </TableCell>
                      <TableCell>
                        <Chip 
                          label={meeting.meeting_type} 
                          size="small"
                          color={meeting.meeting_type === 'BPA' ? 'primary' : 'secondary'}
                        />
                      </TableCell>
                      <TableCell>{meeting.presiding_officer_name || 'Not recorded'}</TableCell>
                      <TableCell>
                        <Box display="flex" alignItems="center" gap={1}>
                          {meeting.quorum_achieved}/{meeting.quorum_required}
                          {meeting.quorum_met ? (
                            <CheckCircle color="success" fontSize="small" />
                          ) : (
                            <Cancel color="error" fontSize="small" />
                          )}
                        </Box>
                      </TableCell>
                      <TableCell>{meeting.total_attendees}</TableCell>
                      <TableCell>
                        {meeting.meeting_package_path ? (
                          <IconButton
                            size="small"
                            color="primary"
                            title="Download Meeting Package"
                            onClick={() => wardAuditApi.downloadMeetingPackage(meeting.record_id)}
                          >
                            <DownloadIcon fontSize="small" />
                          </IconButton>
                        ) : (
                          <Typography variant="caption" color="text.secondary">—</Typography>
                        )}
                      </TableCell>
                      <TableCell>
                        <Box>
                          <Chip
                            label={meeting.meeting_outcome || '—'}
                            size="small"
                            color={
                              meeting.meeting_outcome === 'Passed'
                                ? 'success'
                                : meeting.meeting_outcome === 'Failed'
                                ? 'error'
                                : 'default'
                            }
                          />
                          {meeting.meeting_outcome === 'Passed' && meeting.nominated_councillor_name && (
                            <Typography variant="caption" display="block" color="text.secondary" sx={{ mt: 0.5 }}>
                              <HowToRegIcon sx={{ fontSize: 12, mr: 0.3, verticalAlign: 'middle' }} />
                              {meeting.nominated_councillor_name}
                            </Typography>
                          )}
                        </Box>
                      </TableCell>
                      <TableCell>
                        <Box display="flex" gap={1}>
                          <IconButton
                            size="small"
                            color="primary"
                            title="Edit meeting record"
                          >
                            <EditIcon fontSize="small" />
                          </IconButton>
                          <IconButton
                            size="small"
                            color="error"
                            onClick={() => handleDeleteClick(meeting.record_id)}
                            title="Delete meeting record"
                          >
                            <DeleteIcon fontSize="small" />
                          </IconButton>
                        </Box>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        </CardContent>
      </Card>

      {/* Create Meeting Dialog */}
      <Dialog open={openDialog} onClose={() => setOpenDialog(false)} maxWidth="md" fullWidth>
        <DialogTitle>
          <Box>
            <Typography variant="h6">Record New Ward Meeting</Typography>
            <Typography variant="body2" color="text.secondary">
              {wardName} • {wardMemberCount} members in this ward
            </Typography>
          </Box>
        </DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12} sm={6}>
              <TextField
                select
                fullWidth
                label="Meeting Type"
                value={formData.meeting_type}
                onChange={(e) => handleChange('meeting_type', e.target.value)}
              >
                <MenuItem value="BPA">BPA (Branch People's Assembly)</MenuItem>
                <MenuItem value="BGA">BGA (Branch General Assembly)</MenuItem>
              </TextField>
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                type="date"
                label="Meeting Date"
                value={formData.meeting_date}
                onChange={(e) => handleChange('meeting_date', e.target.value)}
                InputLabelProps={{ shrink: true }}
                required
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label="Presiding Officer"
                value={formData.presiding_officer_name}
                onChange={(e) => handleChange('presiding_officer_name', e.target.value)}
                placeholder="Enter presiding officer's full name"
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label="Secretary"
                value={formData.secretary_name}
                onChange={(e) => handleChange('secretary_name', e.target.value)}
                placeholder="Enter secretary's full name"
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                type="number"
                label="Number of Attendees"
                value={formData.total_attendees}
                onChange={(e) => handleChange('total_attendees', parseInt(e.target.value) || 0)}
                required
                helperText="Enter the number of attendees / signatures from the register"
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                type="number"
                label="Quorum Required"
                value={formData.quorum_required}
                onChange={(e) => handleChange('quorum_required', parseInt(e.target.value) || 0)}
                required
                helperText="Enter the quorum required for this meeting"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                select
                fullWidth
                label="Meeting Outcome"
                value={formData.meeting_outcome}
                onChange={(e) => handleChange('meeting_outcome', e.target.value)}
              >
                <MenuItem value=""><em>Select Outcome</em></MenuItem>
                <MenuItem value="Passed">Passed</MenuItem>
                <MenuItem value="Failed">Failed</MenuItem>
              </TextField>
            </Grid>

            {/* Nominate Councillor — visible only when outcome is Passed */}
            {formData.meeting_outcome === 'Passed' && (
              <Grid item xs={12}>
                <Box
                  sx={{
                    border: '1px solid',
                    borderColor: selectedCouncillor ? 'success.main' : 'primary.main',
                    borderRadius: 2,
                    p: 2,
                    bgcolor: selectedCouncillor ? 'success.50' : 'primary.50',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    gap: 2,
                  }}
                >
                  <Box>
                    <Typography variant="subtitle2" color={selectedCouncillor ? 'success.main' : 'primary.main'}>
                      <HowToRegIcon sx={{ fontSize: 16, mr: 0.5, verticalAlign: 'middle' }} />
                      Nominated Councillor
                    </Typography>
                    {selectedCouncillor ? (
                      <Typography variant="body2" fontWeight="bold">
                        {selectedCouncillor.full_name || selectedCouncillor.name}
                        {(selectedCouncillor.id_number || selectedCouncillor.member_id) && (
                          <Typography component="span" variant="caption" color="text.secondary" sx={{ ml: 1 }}>
                            ID: {selectedCouncillor.id_number || selectedCouncillor.member_id}
                          </Typography>
                        )}
                      </Typography>
                    ) : (
                      <Typography variant="caption" color="text.secondary">
                        No councillor nominated yet
                      </Typography>
                    )}
                  </Box>
                  <Box display="flex" gap={1}>
                    {selectedCouncillor && (
                      <Button
                        size="small"
                        color="error"
                        variant="outlined"
                        onClick={() => {
                          setSelectedCouncillor(null);
                          setFormData(prev => ({ ...prev, nominated_councillor_id: undefined, nominated_councillor_name: undefined }));
                        }}
                      >
                        Remove
                      </Button>
                    )}
                    <Button
                      size="small"
                      variant="contained"
                      startIcon={<HowToRegIcon />}
                      onClick={() => {
                        setCouncillorSearch('');
                        setCouncillorSearchResults([]);
                        setNominateCouncillorOpen(true);
                      }}
                    >
                      {selectedCouncillor ? 'Change Councillor' : 'Nominate Councillor'}
                    </Button>
                  </Box>
                </Box>
              </Grid>
            )}

            {/* Meeting Package Upload */}
            <Grid item xs={12}>
              <Alert severity="info" sx={{ mb: 2 }}>
                <Typography variant="subtitle2" gutterBottom>
                  Meeting Package Upload (Optional)
                </Typography>
                <Typography variant="body2">
                  Upload meeting documents (agenda, minutes, attendance register, resolutions) as a single file or ZIP.
                  This package will be available for national admin review in case of disputes.
                </Typography>
              </Alert>
              <Box
                sx={{
                  border: '2px dashed',
                  borderColor: meetingPackageFile ? 'success.main' : 'grey.400',
                  borderRadius: 2,
                  p: 3,
                  textAlign: 'center',
                  bgcolor: meetingPackageFile ? 'success.50' : 'grey.50',
                  cursor: 'pointer',
                  transition: 'all 0.2s ease',
                  '&:hover': {
                    borderColor: 'primary.main',
                    bgcolor: 'primary.50',
                  },
                }}
                onClick={() => document.getElementById('meeting-package-input')?.click()}
              >
                <input
                  id="meeting-package-input"
                  type="file"
                  hidden
                  accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx,.zip"
                  onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (file) {
                      if (file.size > 25 * 1024 * 1024) {
                        alert('File size must be less than 25MB');
                        return;
                      }
                      setMeetingPackageFile(file);
                    }
                  }}
                />
                {meetingPackageFile ? (
                  <Box>
                    <CheckCircle color="success" sx={{ fontSize: 40, mb: 1 }} />
                    <Typography variant="body1" fontWeight="bold" color="success.main">
                      {meetingPackageFile.name}
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      {(meetingPackageFile.size / (1024 * 1024)).toFixed(2)} MB
                    </Typography>
                    <Box sx={{ mt: 1 }}>
                      <Button
                        size="small"
                        color="error"
                        onClick={(e) => {
                          e.stopPropagation();
                          setMeetingPackageFile(null);
                          const input = document.getElementById('meeting-package-input') as HTMLInputElement;
                          if (input) input.value = '';
                        }}
                      >
                        Remove File
                      </Button>
                    </Box>
                  </Box>
                ) : (
                  <Box>
                    <CloudUploadIcon sx={{ fontSize: 40, mb: 1, color: 'grey.500' }} />
                    <Typography variant="body1" color="text.secondary">
                      Click to upload meeting package
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      PDF, JPEG, PNG, DOC, DOCX, XLS, XLSX, ZIP — Max 25MB
                    </Typography>
                  </Box>
                )}
              </Box>
            </Grid>

            {/* Quorum Verification */}
            <Grid item xs={12}>
              <FormControlLabel
                control={
                  <Checkbox
                    checked={formData.quorum_verified_manually}
                    onChange={(e) => handleChange('quorum_verified_manually', e.target.checked)}
                    color="primary"
                  />
                }
                label={`I verify the quorum is correct — Attendees: ${formData.total_attendees} | Required: ${formData.quorum_required}`}
              />
              {formData.quorum_verified_manually && (
                <TextField
                  fullWidth
                  multiline
                  rows={2}
                  label="Quorum Verification Notes (Required)"
                  value={formData.quorum_verification_notes}
                  onChange={(e) => handleChange('quorum_verification_notes', e.target.value)}
                  placeholder="Add notes about the quorum verification"
                  sx={{ mt: 1 }}
                  required
                />
              )}
            </Grid>

            {/* Meeting Attendance Verification */}
            <Grid item xs={12}>
              <FormControlLabel
                control={
                  <Checkbox
                    checked={formData.meeting_took_place_verified}
                    onChange={(e) => handleChange('meeting_took_place_verified', e.target.checked)}
                    color="primary"
                  />
                }
                label="I confirm that the meeting took place as recorded"
              />
              {formData.meeting_took_place_verified && (
                <TextField
                  fullWidth
                  multiline
                  rows={2}
                  label="Meeting Verification Notes"
                  value={formData.meeting_verification_notes}
                  onChange={(e) => handleChange('meeting_verification_notes', e.target.value)}
                  placeholder="Add any notes about meeting attendance"
                  sx={{ mt: 1 }}
                />
              )}
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenDialog(false)}>Cancel</Button>
          <Button 
            onClick={handleSubmit} 
            variant="contained"
            disabled={createMeetingMutation.isPending}
          >
            {createMeetingMutation.isPending ? 'Saving...' : 'Save Meeting'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={deleteConfirmOpen} onClose={handleDeleteCancel}>
        <DialogTitle>Confirm Delete</DialogTitle>
        <DialogContent>
          <Alert severity="warning" sx={{ mb: 2 }}>
            <Typography variant="body2">
              Are you sure you want to delete this meeting record? This action cannot be undone.
            </Typography>
          </Alert>
          <Typography variant="body2">
            This will permanently remove the meeting record from the system.
          </Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleDeleteCancel}>Cancel</Button>
          <Button
            onClick={handleDeleteConfirm}
            variant="contained"
            color="error"
            disabled={deleteMeetingMutation.isPending}
          >
            {deleteMeetingMutation.isPending ? 'Deleting...' : 'Delete'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Nominate Councillor Modal */}
      <Dialog
        open={nominateCouncillorOpen}
        onClose={() => setNominateCouncillorOpen(false)}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>
          <Box>
            <Typography variant="h6">
              <HowToRegIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
              Nominate Councillor
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Search by ID number or name to find and select a councillor
            </Typography>
          </Box>
        </DialogTitle>
        <DialogContent>
          <TextField
            fullWidth
            placeholder="Search by ID number or name..."
            value={councillorSearch}
            onChange={(e) => handleCouncillorSearch(e.target.value)}
            sx={{ mb: 2, mt: 1 }}
            InputProps={{
              startAdornment: (
                <InputAdornment position="start">
                  {councillorSearchLoading ? <CircularProgress size={18} /> : <SearchIcon />}
                </InputAdornment>
              ),
            }}
            autoFocus
          />

          {councillorSearch.trim().length > 0 && councillorSearch.trim().length < 2 && (
            <Alert severity="info" sx={{ mb: 1 }}>Type at least 2 characters to search.</Alert>
          )}

          {councillorSearchResults.length > 0 ? (
            <TableContainer component={Paper} variant="outlined" sx={{ maxHeight: 320 }}>
              <Table size="small" stickyHeader>
                <TableHead>
                  <TableRow>
                    <TableCell>Name</TableCell>
                    <TableCell>ID Number</TableCell>
                    <TableCell>Cell</TableCell>
                    <TableCell align="center">Select</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {councillorSearchResults.map((member: any) => (
                    <TableRow
                      key={member.member_id || member.id}
                      hover
                      sx={{ cursor: 'pointer' }}
                      onClick={() => handleSelectCouncillor(member)}
                    >
                      <TableCell>
                        <Typography variant="body2" fontWeight="medium">
                          {member.full_name || member.name}
                        </Typography>
                      </TableCell>
                      <TableCell>{member.id_number || '—'}</TableCell>
                      <TableCell>{member.cell_number || '—'}</TableCell>
                      <TableCell align="center">
                        <Button size="small" variant="contained" onClick={() => handleSelectCouncillor(member)}>
                          Select
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          ) : councillorSearch.trim().length >= 2 && !councillorSearchLoading ? (
            <Alert severity="info">No members found matching "{councillorSearch}".</Alert>
          ) : null}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setNominateCouncillorOpen(false)}>Cancel</Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default WardMeetingManagement;

