import React, { useState } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  MenuItem,
  Grid,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Chip,
  IconButton,
  Alert,
  FormControlLabel,
  Checkbox,
  Autocomplete,
} from '@mui/material';
import { Add as AddIcon, Edit as EditIcon, CheckCircle, Cancel, Delete as DeleteIcon } from '@mui/icons-material';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { wardAuditApi } from '../../services/wardAuditApi';

interface WardMeetingManagementProps {
  wardCode: string;
  wardName: string;
  provinceCode: string;
}

interface MeetingFormData {
  meeting_id?: number; // Optional - will be auto-generated by backend
  meeting_type: 'BPA' | 'BGA';
  presiding_officer_id: number | '';
  secretary_id: number | '';
  quorum_required: number;
  quorum_achieved: number;
  total_attendees: number;
  meeting_outcome: string;
  key_decisions: string;
  action_items: string;
  next_meeting_date: string;
  quorum_verified_manually: boolean;
  quorum_verification_notes: string;
  meeting_took_place_verified: boolean;
  meeting_verification_notes: string;
}

const WardMeetingManagement: React.FC<WardMeetingManagementProps> = ({ wardCode, wardName, provinceCode }) => {
  const queryClient = useQueryClient();
  const [openDialog, setOpenDialog] = useState(false);
  const [deleteConfirmOpen, setDeleteConfirmOpen] = useState(false);
  const [recordToDelete, setRecordToDelete] = useState<number | null>(null);
  const [formData, setFormData] = useState<MeetingFormData>({
    // meeting_id removed - will be auto-generated by backend
    meeting_type: 'BPA',
    presiding_officer_id: '',
    secretary_id: '',
    quorum_required: 50,
    quorum_achieved: 0,
    total_attendees: 0,
    meeting_outcome: '',
    key_decisions: '',
    action_items: '',
    next_meeting_date: '',
    quorum_verified_manually: false,
    quorum_verification_notes: '',
    meeting_took_place_verified: false,
    meeting_verification_notes: '',
  });

  // Search states for autocomplete
  const [presidingOfficerSearch, setPresidingOfficerSearch] = useState('');
  const [secretarySearch, setSecretarySearch] = useState('');
  const [presidingOfficerOptions, setPresidingOfficerOptions] = useState<any[]>([]);
  const [secretaryOptions, setSecretaryOptions] = useState<any[]>([]);

  // Fetch ward meetings
  const { data: meetings = [], isLoading } = useQuery({
    queryKey: ['ward-meetings', wardCode],
    queryFn: () => wardAuditApi.getWardMeetings(wardCode),
  });

  // Fetch ward member count
  const { data: wardMemberCount = 0 } = useQuery({
    queryKey: ['ward-member-count', wardCode],
    queryFn: async () => {
      const compliance = await wardAuditApi.getWardCompliance(wardCode);
      return compliance.total_members || 0;
    },
    enabled: !!wardCode,
    staleTime: 60000, // Cache for 1 minute
  });

  // Search for presiding officer (from province) - only when user types
  const { data: presidingOfficerResults = [], isLoading: presidingOfficerLoading } = useQuery({
    queryKey: ['search-presiding-officer', provinceCode, presidingOfficerSearch],
    queryFn: () => wardAuditApi.searchMembersByProvince(provinceCode, presidingOfficerSearch),
    enabled: !!provinceCode && presidingOfficerSearch.length >= 2,
    staleTime: 30000, // Cache for 30 seconds
  });

  // Search for secretary (from ward) - only when user types
  const { data: secretaryResults = [], isLoading: secretaryLoading } = useQuery({
    queryKey: ['search-secretary', wardCode, secretarySearch],
    queryFn: () => wardAuditApi.searchMembersByWard(wardCode, secretarySearch),
    enabled: !!wardCode && secretarySearch.length >= 2,
    staleTime: 30000, // Cache for 30 seconds
  });

  // Update options when search results change
  React.useEffect(() => {
    if (presidingOfficerResults.length > 0) {
      setPresidingOfficerOptions(presidingOfficerResults);
    }
  }, [presidingOfficerResults]);

  React.useEffect(() => {
    if (secretaryResults.length > 0) {
      setSecretaryOptions(secretaryResults);
    }
  }, [secretaryResults]);

  // Calculate quorum requirement: (Total Members / 2) + 1
  const quorumRequired = React.useMemo(() => {
    return Math.floor(wardMemberCount / 2) + 1;
  }, [wardMemberCount]);

  // Update quorum_required when wardMemberCount changes
  React.useEffect(() => {
    setFormData(prev => ({
      ...prev,
      quorum_required: quorumRequired
    }));
  }, [quorumRequired]);

  // Check if quorum is achieved based on total_attendees
  const isQuorumAchieved = React.useMemo(() => {
    return formData.total_attendees >= quorumRequired;
  }, [formData.total_attendees, quorumRequired]);

  // Auto-update quorum_achieved when total_attendees changes
  React.useEffect(() => {
    setFormData(prev => ({
      ...prev,
      quorum_achieved: prev.total_attendees
    }));
  }, [formData.total_attendees]);

  // Create meeting mutation
  const createMeetingMutation = useMutation({
    mutationFn: (data: MeetingFormData) => wardAuditApi.createMeetingRecord(wardCode, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ward-meetings', wardCode] });
      queryClient.invalidateQueries({ queryKey: ['ward-compliance-details', wardCode] });
      setOpenDialog(false);
      resetForm();
    },
  });

  // Delete meeting mutation
  const deleteMeetingMutation = useMutation({
    mutationFn: (recordId: number) => wardAuditApi.deleteMeetingRecord(recordId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ward-meetings', wardCode] });
      queryClient.invalidateQueries({ queryKey: ['ward-compliance-details', wardCode] });
      setDeleteConfirmOpen(false);
      setRecordToDelete(null);
    },
  });

  const resetForm = () => {
    setFormData({
      // meeting_id removed - will be auto-generated by backend
      meeting_type: 'BPA',
      presiding_officer_id: '',
      secretary_id: '',
      quorum_required: 50,
      quorum_achieved: 0,
      total_attendees: 0,
      meeting_outcome: '',
      key_decisions: '',
      action_items: '',
      next_meeting_date: '',
      quorum_verified_manually: false,
      quorum_verification_notes: '',
      meeting_took_place_verified: false,
      meeting_verification_notes: '',
    });
  };

  const handleSubmit = () => {
    createMeetingMutation.mutate(formData);
  };

  const handleChange = (field: keyof MeetingFormData, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleDeleteClick = (recordId: number) => {
    setRecordToDelete(recordId);
    setDeleteConfirmOpen(true);
  };

  const handleDeleteConfirm = () => {
    if (recordToDelete !== null) {
      deleteMeetingMutation.mutate(recordToDelete);
    }
  };

  const handleDeleteCancel = () => {
    setDeleteConfirmOpen(false);
    setRecordToDelete(null);
  };

  // const quorumMet = formData.quorum_achieved >= formData.quorum_required;

  return (
    <Box>
      <Card>
        <CardContent>
          <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
            <Typography variant="h6">
              Ward Meeting Records - {wardName}
            </Typography>
            <Button
              variant="contained"
              startIcon={<AddIcon />}
              onClick={() => setOpenDialog(true)}
            >
              Record New Meeting
            </Button>
          </Box>

          {isLoading ? (
            <Typography>Loading meetings...</Typography>
          ) : meetings.length === 0 ? (
            <Alert severity="info">
              No meeting records found. Click "Record New Meeting" to add the first meeting.
            </Alert>
          ) : (
            <TableContainer component={Paper}>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Date</TableCell>
                    <TableCell>Type</TableCell>
                    <TableCell>Presiding Officer</TableCell>
                    <TableCell>Quorum</TableCell>
                    <TableCell>Attendees</TableCell>
                    <TableCell>Outcome</TableCell>
                    <TableCell>Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {meetings.map((meeting: any) => (
                    <TableRow key={meeting.record_id}>
                      <TableCell>
                        {new Date(meeting.created_at).toLocaleDateString()}
                      </TableCell>
                      <TableCell>
                        <Chip 
                          label={meeting.meeting_type} 
                          size="small"
                          color={meeting.meeting_type === 'BPA' ? 'primary' : 'secondary'}
                        />
                      </TableCell>
                      <TableCell>{meeting.presiding_officer_name || 'Not recorded'}</TableCell>
                      <TableCell>
                        <Box display="flex" alignItems="center" gap={1}>
                          {meeting.quorum_achieved}/{meeting.quorum_required}
                          {meeting.quorum_met ? (
                            <CheckCircle color="success" fontSize="small" />
                          ) : (
                            <Cancel color="error" fontSize="small" />
                          )}
                        </Box>
                      </TableCell>
                      <TableCell>{meeting.total_attendees}</TableCell>
                      <TableCell>{meeting.meeting_outcome || '-'}</TableCell>
                      <TableCell>
                        <Box display="flex" gap={1}>
                          <IconButton
                            size="small"
                            color="primary"
                            title="Edit meeting record"
                          >
                            <EditIcon fontSize="small" />
                          </IconButton>
                          <IconButton
                            size="small"
                            color="error"
                            onClick={() => handleDeleteClick(meeting.record_id)}
                            title="Delete meeting record"
                          >
                            <DeleteIcon fontSize="small" />
                          </IconButton>
                        </Box>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        </CardContent>
      </Card>

      {/* Create Meeting Dialog */}
      <Dialog open={openDialog} onClose={() => setOpenDialog(false)} maxWidth="md" fullWidth>
        <DialogTitle>
          <Box>
            <Typography variant="h6">Record New Ward Meeting</Typography>
            <Typography variant="body2" color="text.secondary">
              {wardName} • {wardMemberCount} members in this ward
            </Typography>
          </Box>
        </DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12} sm={6}>
              <TextField
                select
                fullWidth
                label="Meeting Type"
                value={formData.meeting_type}
                onChange={(e) => handleChange('meeting_type', e.target.value)}
              >
                <MenuItem value="BPA">BPA (Branch People's Assembly)</MenuItem>
                <MenuItem value="BGA">BGA (Branch General Assembly)</MenuItem>
              </TextField>
            </Grid>
            {/* Criterion 4: Presiding Officer Selection (Province-Filtered) */}
            <Grid item xs={12}>
              <Alert severity="info" sx={{ mb: 2 }}>
                <Typography variant="subtitle2" gutterBottom>
                  Criterion 4: Presiding Officer & Secretary Selection
                </Typography>
                <Typography variant="body2">
                  • Presiding Officer: Search from members in the same province<br />
                  • Secretary: Search from members in this ward ({wardName}) - {wardMemberCount} total members
                </Typography>
              </Alert>
            </Grid>
            <Grid item xs={12} sm={6}>
              <Autocomplete
                options={presidingOfficerOptions}
                getOptionLabel={(option) =>
                  option.full_name
                    ? `${option.full_name} (${option.id_number || 'N/A'})`
                    : ''
                }
                value={presidingOfficerOptions.find((m: any) => m.member_id === formData.presiding_officer_id) || null}
                onChange={(_, newValue) => {
                  handleChange('presiding_officer_id', newValue?.member_id || '');
                }}
                onInputChange={(_, newInputValue) => {
                  setPresidingOfficerSearch(newInputValue);
                }}
                loading={presidingOfficerLoading}
                filterOptions={(x) => x} // Disable client-side filtering
                noOptionsText={
                  presidingOfficerSearch.length < 2
                    ? 'Type at least 2 characters to search...'
                    : 'No members found'
                }
                renderInput={(params) => (
                  <TextField
                    {...params}
                    label="Presiding Officer"
                    placeholder="Type to search by name or ID..."
                    helperText={
                      presidingOfficerLoading
                        ? 'Searching...'
                        : presidingOfficerSearch.length < 2
                        ? 'Type at least 2 characters to search'
                        : `${presidingOfficerOptions.length} members found`
                    }
                  />
                )}
                renderOption={(props, option) => (
                  <li {...props} key={option.member_id}>
                    <Box>
                      <Typography variant="body2">
                        <strong>{option.full_name}</strong>
                      </Typography>
                      <Typography variant="caption" color="text.secondary">
                        ID: {option.id_number || 'N/A'} | Ward: {option.ward_name || 'N/A'} | Status: {option.membership_status || 'N/A'}
                      </Typography>
                    </Box>
                  </li>
                )}
                isOptionEqualToValue={(option, value) => option.member_id === value.member_id}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <Autocomplete
                options={secretaryOptions}
                getOptionLabel={(option) =>
                  option.full_name
                    ? `${option.full_name} (${option.id_number || 'N/A'})`
                    : ''
                }
                value={secretaryOptions.find((m: any) => m.member_id === formData.secretary_id) || null}
                onChange={(_, newValue) => {
                  handleChange('secretary_id', newValue?.member_id || '');
                }}
                onInputChange={(_, newInputValue) => {
                  setSecretarySearch(newInputValue);
                }}
                loading={secretaryLoading}
                filterOptions={(x) => x} // Disable client-side filtering
                noOptionsText={
                  secretarySearch.length < 2
                    ? 'Type at least 2 characters to search...'
                    : 'No members found in this ward'
                }
                renderInput={(params) => (
                  <TextField
                    {...params}
                    label="Secretary (from this ward)"
                    placeholder="Type to search by name or ID..."
                    helperText={
                      secretaryLoading
                        ? 'Searching...'
                        : secretarySearch.length < 2
                        ? 'Type at least 2 characters to search'
                        : `${secretaryOptions.length} members found in ${wardName}`
                    }
                  />
                )}
                renderOption={(props, option) => (
                  <li {...props} key={option.member_id}>
                    <Box>
                      <Typography variant="body2">
                        <strong>{option.full_name}</strong>
                      </Typography>
                      <Typography variant="caption" color="text.secondary">
                        ID: {option.id_number || 'N/A'} | Ward: {option.ward_name || 'N/A'} | Status: {option.membership_status || 'N/A'}
                      </Typography>
                    </Box>
                  </li>
                )}
                isOptionEqualToValue={(option, value) => option.member_id === value.member_id}
              />
            </Grid>
            {/* Criterion 2: Quorum Verification */}
            <Grid item xs={12}>
              <Alert severity="warning" sx={{ mb: 2 }}>
                <Typography variant="subtitle2" gutterBottom>
                  Criterion 2: Quorum Verification
                </Typography>
                <Typography variant="body2">
                  <strong>Formula:</strong> Quorum Required = (Total Ward Members ÷ 2) + 1<br />
                  <strong>Calculation:</strong> ({wardMemberCount} ÷ 2) + 1 = <strong>{quorumRequired} members required</strong><br />
                  <strong>Current Status:</strong> {isQuorumAchieved ? '✓ Quorum ACHIEVED' : '✗ Quorum NOT achieved'}
                </Typography>
              </Alert>
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                type="number"
                label="Total Attendees / Signatures from Register"
                value={formData.total_attendees}
                onChange={(e) => handleChange('total_attendees', parseInt(e.target.value) || 0)}
                required
                helperText={`Enter number of attendees or signatures (Quorum: ${quorumRequired})`}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                type="number"
                label="Quorum Required (Auto-Calculated)"
                value={formData.quorum_required}
                disabled
                InputProps={{
                  readOnly: true,
                }}
                helperText={`Formula: (${wardMemberCount} ÷ 2) + 1 = ${quorumRequired}`}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                type="number"
                label="Quorum Achieved (Auto-Filled)"
                value={formData.quorum_achieved}
                disabled
                InputProps={{
                  readOnly: true,
                }}
                helperText={isQuorumAchieved ? '✓ Quorum met' : '✗ Quorum not met'}
                error={!isQuorumAchieved}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <Box sx={{
                p: 2,
                border: 1,
                borderRadius: 1,
                borderColor: isQuorumAchieved ? 'success.main' : 'error.main',
                bgcolor: isQuorumAchieved ? 'success.light' : 'error.light'
              }}>
                <Typography variant="subtitle2" gutterBottom>
                  Quorum Status
                </Typography>
                <Typography variant="h6" color={isQuorumAchieved ? 'success.dark' : 'error.dark'}>
                  {isQuorumAchieved ? '✓ QUORUM REACHED' : '✗ QUORUM NOT REACHED'}
                </Typography>
                <Typography variant="body2" sx={{ mt: 1 }}>
                  {formData.total_attendees} / {quorumRequired} required
                </Typography>
              </Box>
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Meeting Outcome"
                value={formData.meeting_outcome}
                onChange={(e) => handleChange('meeting_outcome', e.target.value)}
                placeholder="e.g., Successful, Postponed, Cancelled"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                multiline
                rows={3}
                label="Key Decisions"
                value={formData.key_decisions}
                onChange={(e) => handleChange('key_decisions', e.target.value)}
                placeholder="Summarize key decisions made during the meeting"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                multiline
                rows={2}
                label="Action Items"
                value={formData.action_items}
                onChange={(e) => handleChange('action_items', e.target.value)}
                placeholder="List action items and follow-ups"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                type="date"
                label="Next Meeting Date"
                value={formData.next_meeting_date}
                onChange={(e) => handleChange('next_meeting_date', e.target.value)}
                InputLabelProps={{ shrink: true }}
              />
            </Grid>

            {/* Criterion 2: Manual Quorum Verification */}
            <Grid item xs={12}>
              <Alert
                severity={isQuorumAchieved ? "success" : "warning"}
                sx={{ mb: 2 }}
              >
                <Typography variant="subtitle2" gutterBottom>
                  Criterion 2: Final Quorum Verification
                </Typography>
                <Typography variant="body2">
                  <strong>System Calculation:</strong> {isQuorumAchieved ? '✓ Quorum ACHIEVED' : '✗ Quorum NOT achieved'}<br />
                  <strong>Attendees:</strong> {formData.total_attendees} / {quorumRequired} required<br />
                  <strong>Formula:</strong> ({wardMemberCount} ÷ 2) + 1 = {quorumRequired}<br />
                  <br />
                  Please verify this calculation matches the attendance register and confirm below.
                </Typography>
              </Alert>
              <FormControlLabel
                control={
                  <Checkbox
                    checked={formData.quorum_verified_manually}
                    onChange={(e) => handleChange('quorum_verified_manually', e.target.checked)}
                    color={isQuorumAchieved ? "success" : "warning"}
                  />
                }
                label={
                  isQuorumAchieved
                    ? "✓ I verify that the meeting quorum was met (system shows ACHIEVED)"
                    : "⚠ I verify the quorum status (system shows NOT achieved)"
                }
              />
              {formData.quorum_verified_manually && (
                <TextField
                  fullWidth
                  multiline
                  rows={2}
                  label="Quorum Verification Notes (Required)"
                  value={formData.quorum_verification_notes}
                  onChange={(e) => handleChange('quorum_verification_notes', e.target.value)}
                  placeholder={
                    isQuorumAchieved
                      ? "Confirm attendance register matches the system calculation"
                      : "Explain why quorum was not met or provide additional context"
                  }
                  sx={{ mt: 2 }}
                  required
                />
              )}
            </Grid>

            {/* Criterion 3: Manual Meeting Attendance Verification */}
            <Grid item xs={12}>
              <Alert severity="info" sx={{ mb: 2 }}>
                <Typography variant="subtitle2" gutterBottom>
                  Criterion 3: Meeting Attendance
                </Typography>
                <Typography variant="body2">
                  Confirm that the required meeting actually took place with proper attendance.
                </Typography>
              </Alert>
              <FormControlLabel
                control={
                  <Checkbox
                    checked={formData.meeting_took_place_verified}
                    onChange={(e) => handleChange('meeting_took_place_verified', e.target.checked)}
                    color="primary"
                  />
                }
                label="I confirm that the meeting took place as recorded"
              />
              {formData.meeting_took_place_verified && (
                <TextField
                  fullWidth
                  multiline
                  rows={2}
                  label="Meeting Verification Notes"
                  value={formData.meeting_verification_notes}
                  onChange={(e) => handleChange('meeting_verification_notes', e.target.value)}
                  placeholder="Add any notes about meeting attendance"
                  sx={{ mt: 2 }}
                />
              )}
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenDialog(false)}>Cancel</Button>
          <Button 
            onClick={handleSubmit} 
            variant="contained"
            disabled={createMeetingMutation.isPending}
          >
            {createMeetingMutation.isPending ? 'Saving...' : 'Save Meeting'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={deleteConfirmOpen} onClose={handleDeleteCancel}>
        <DialogTitle>Confirm Delete</DialogTitle>
        <DialogContent>
          <Alert severity="warning" sx={{ mb: 2 }}>
            <Typography variant="body2">
              Are you sure you want to delete this meeting record? This action cannot be undone.
            </Typography>
          </Alert>
          <Typography variant="body2">
            This will permanently remove the meeting record from the system.
          </Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleDeleteCancel}>Cancel</Button>
          <Button
            onClick={handleDeleteConfirm}
            variant="contained"
            color="error"
            disabled={deleteMeetingMutation.isPending}
          >
            {deleteMeetingMutation.isPending ? 'Deleting...' : 'Delete'}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default WardMeetingManagement;

