import React, { useState } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  MenuItem,
  Grid,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Chip,
  IconButton,
  Alert,
  FormControlLabel,
  Checkbox,
  Autocomplete,
} from '@mui/material';
import { Add as AddIcon, Edit as EditIcon, CheckCircle, Cancel } from '@mui/icons-material';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { wardAuditApi } from '../../services/wardAuditApi';

interface WardMeetingManagementProps {
  wardCode: string;
  wardName: string;
  provinceCode: string;
}

interface MeetingFormData {
  meeting_id?: number; // Optional - will be auto-generated by backend
  meeting_type: 'BPA' | 'BGA';
  presiding_officer_id: number | '';
  secretary_id: number | '';
  quorum_required: number;
  quorum_achieved: number;
  total_attendees: number;
  meeting_outcome: string;
  key_decisions: string;
  action_items: string;
  next_meeting_date: string;
  quorum_verified_manually: boolean;
  quorum_verification_notes: string;
  meeting_took_place_verified: boolean;
  meeting_verification_notes: string;
}

const WardMeetingManagement: React.FC<WardMeetingManagementProps> = ({ wardCode, wardName, provinceCode }) => {
  const queryClient = useQueryClient();
  const [openDialog, setOpenDialog] = useState(false);
  const [formData, setFormData] = useState<MeetingFormData>({
    // meeting_id removed - will be auto-generated by backend
    meeting_type: 'BPA',
    presiding_officer_id: '',
    secretary_id: '',
    quorum_required: 50,
    quorum_achieved: 0,
    total_attendees: 0,
    meeting_outcome: '',
    key_decisions: '',
    action_items: '',
    next_meeting_date: '',
    quorum_verified_manually: false,
    quorum_verification_notes: '',
    meeting_took_place_verified: false,
    meeting_verification_notes: '',
  });

  // Fetch ward meetings
  const { data: meetings = [], isLoading } = useQuery({
    queryKey: ['ward-meetings', wardCode],
    queryFn: () => wardAuditApi.getWardMeetings(wardCode),
  });

  // Fetch eligible members from the same province (Criterion 4)
  const { data: eligibleMembers = [], isLoading: membersLoading } = useQuery({
    queryKey: ['eligible-members', provinceCode],
    queryFn: () => wardAuditApi.getMembersByProvince(provinceCode),
    enabled: !!provinceCode,
  });

  // Create meeting mutation
  const createMeetingMutation = useMutation({
    mutationFn: (data: MeetingFormData) => wardAuditApi.createMeetingRecord(wardCode, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ward-meetings', wardCode] });
      queryClient.invalidateQueries({ queryKey: ['ward-compliance-details', wardCode] });
      setOpenDialog(false);
      resetForm();
    },
  });

  const resetForm = () => {
    setFormData({
      // meeting_id removed - will be auto-generated by backend
      meeting_type: 'BPA',
      presiding_officer_id: '',
      secretary_id: '',
      quorum_required: 50,
      quorum_achieved: 0,
      total_attendees: 0,
      meeting_outcome: '',
      key_decisions: '',
      action_items: '',
      next_meeting_date: '',
      quorum_verified_manually: false,
      quorum_verification_notes: '',
      meeting_took_place_verified: false,
      meeting_verification_notes: '',
    });
  };

  const handleSubmit = () => {
    createMeetingMutation.mutate(formData);
  };

  const handleChange = (field: keyof MeetingFormData, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const quorumMet = formData.quorum_achieved >= formData.quorum_required;

  return (
    <Box>
      <Card>
        <CardContent>
          <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
            <Typography variant="h6">
              Ward Meeting Records - {wardName}
            </Typography>
            <Button
              variant="contained"
              startIcon={<AddIcon />}
              onClick={() => setOpenDialog(true)}
            >
              Record New Meeting
            </Button>
          </Box>

          {isLoading ? (
            <Typography>Loading meetings...</Typography>
          ) : meetings.length === 0 ? (
            <Alert severity="info">
              No meeting records found. Click "Record New Meeting" to add the first meeting.
            </Alert>
          ) : (
            <TableContainer component={Paper}>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Date</TableCell>
                    <TableCell>Type</TableCell>
                    <TableCell>Presiding Officer</TableCell>
                    <TableCell>Quorum</TableCell>
                    <TableCell>Attendees</TableCell>
                    <TableCell>Outcome</TableCell>
                    <TableCell>Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {meetings.map((meeting: any) => (
                    <TableRow key={meeting.record_id}>
                      <TableCell>
                        {new Date(meeting.created_at).toLocaleDateString()}
                      </TableCell>
                      <TableCell>
                        <Chip 
                          label={meeting.meeting_type} 
                          size="small"
                          color={meeting.meeting_type === 'BPA' ? 'primary' : 'secondary'}
                        />
                      </TableCell>
                      <TableCell>{meeting.presiding_officer_name || 'Not recorded'}</TableCell>
                      <TableCell>
                        <Box display="flex" alignItems="center" gap={1}>
                          {meeting.quorum_achieved}/{meeting.quorum_required}
                          {meeting.quorum_met ? (
                            <CheckCircle color="success" fontSize="small" />
                          ) : (
                            <Cancel color="error" fontSize="small" />
                          )}
                        </Box>
                      </TableCell>
                      <TableCell>{meeting.total_attendees}</TableCell>
                      <TableCell>{meeting.meeting_outcome || '-'}</TableCell>
                      <TableCell>
                        <IconButton size="small" color="primary">
                          <EditIcon fontSize="small" />
                        </IconButton>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        </CardContent>
      </Card>

      {/* Create Meeting Dialog */}
      <Dialog open={openDialog} onClose={() => setOpenDialog(false)} maxWidth="md" fullWidth>
        <DialogTitle>Record New Ward Meeting</DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12} sm={6}>
              <TextField
                select
                fullWidth
                label="Meeting Type"
                value={formData.meeting_type}
                onChange={(e) => handleChange('meeting_type', e.target.value)}
              >
                <MenuItem value="BPA">BPA (Branch People's Assembly)</MenuItem>
                <MenuItem value="BGA">BGA (Branch General Assembly)</MenuItem>
              </TextField>
            </Grid>
            {/* Criterion 4: Presiding Officer Selection (Province-Filtered) */}
            <Grid item xs={12}>
              <Alert severity="info" sx={{ mb: 2 }}>
                <Typography variant="subtitle2" gutterBottom>
                  Criterion 4: Presiding Officer Information
                </Typography>
                <Typography variant="body2">
                  Select a presiding officer from members in the same province as this ward.
                </Typography>
              </Alert>
            </Grid>
            <Grid item xs={12} sm={6}>
              <Autocomplete
                options={eligibleMembers}
                getOptionLabel={(option) =>
                  option.full_name
                    ? `${option.full_name} (${option.id_number || 'N/A'})`
                    : ''
                }
                value={eligibleMembers.find((m: any) => m.member_id === formData.presiding_officer_id) || null}
                onChange={(_, newValue) => {
                  handleChange('presiding_officer_id', newValue?.member_id || '');
                }}
                loading={membersLoading}
                renderInput={(params) => (
                  <TextField
                    {...params}
                    label="Presiding Officer"
                    helperText={
                      membersLoading
                        ? 'Loading members...'
                        : `${eligibleMembers.length} eligible members from this province`
                    }
                  />
                )}
                renderOption={(props, option) => (
                  <li {...props} key={option.member_id}>
                    <Box>
                      <Typography variant="body2">
                        <strong>{option.full_name}</strong>
                      </Typography>
                      <Typography variant="caption" color="text.secondary">
                        ID: {option.id_number || 'N/A'} | Ward: {option.ward_name || 'N/A'} | Status: {option.membership_status || 'N/A'}
                      </Typography>
                    </Box>
                  </li>
                )}
                isOptionEqualToValue={(option, value) => option.member_id === value.member_id}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <Autocomplete
                options={eligibleMembers}
                getOptionLabel={(option) =>
                  option.full_name
                    ? `${option.full_name} (${option.id_number || 'N/A'})`
                    : ''
                }
                value={eligibleMembers.find((m: any) => m.member_id === formData.secretary_id) || null}
                onChange={(_, newValue) => {
                  handleChange('secretary_id', newValue?.member_id || '');
                }}
                loading={membersLoading}
                renderInput={(params) => (
                  <TextField
                    {...params}
                    label="Secretary"
                    helperText={
                      membersLoading
                        ? 'Loading members...'
                        : `${eligibleMembers.length} eligible members from this province`
                    }
                  />
                )}
                renderOption={(props, option) => (
                  <li {...props} key={option.member_id}>
                    <Box>
                      <Typography variant="body2">
                        <strong>{option.full_name}</strong>
                      </Typography>
                      <Typography variant="caption" color="text.secondary">
                        ID: {option.id_number || 'N/A'} | Ward: {option.ward_name || 'N/A'} | Status: {option.membership_status || 'N/A'}
                      </Typography>
                    </Box>
                  </li>
                )}
                isOptionEqualToValue={(option, value) => option.member_id === value.member_id}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                type="number"
                label="Total Attendees"
                value={formData.total_attendees}
                onChange={(e) => handleChange('total_attendees', parseInt(e.target.value) || 0)}
                required
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                type="number"
                label="Quorum Required"
                value={formData.quorum_required}
                onChange={(e) => handleChange('quorum_required', parseInt(e.target.value) || 0)}
                required
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                type="number"
                label="Quorum Achieved"
                value={formData.quorum_achieved}
                onChange={(e) => handleChange('quorum_achieved', parseInt(e.target.value) || 0)}
                required
                helperText={quorumMet ? '✓ Quorum met' : '✗ Quorum not met'}
                error={!quorumMet}
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Meeting Outcome"
                value={formData.meeting_outcome}
                onChange={(e) => handleChange('meeting_outcome', e.target.value)}
                placeholder="e.g., Successful, Postponed, Cancelled"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                multiline
                rows={3}
                label="Key Decisions"
                value={formData.key_decisions}
                onChange={(e) => handleChange('key_decisions', e.target.value)}
                placeholder="Summarize key decisions made during the meeting"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                multiline
                rows={2}
                label="Action Items"
                value={formData.action_items}
                onChange={(e) => handleChange('action_items', e.target.value)}
                placeholder="List action items and follow-ups"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                type="date"
                label="Next Meeting Date"
                value={formData.next_meeting_date}
                onChange={(e) => handleChange('next_meeting_date', e.target.value)}
                InputLabelProps={{ shrink: true }}
              />
            </Grid>

            {/* Criterion 2: Manual Quorum Verification */}
            <Grid item xs={12}>
              <Alert severity="info" sx={{ mb: 2 }}>
                <Typography variant="subtitle2" gutterBottom>
                  Criterion 2: Meeting Quorum Verification
                </Typography>
                <Typography variant="body2">
                  Manually verify that the meeting quorum was met according to organizational requirements.
                </Typography>
              </Alert>
              <FormControlLabel
                control={
                  <Checkbox
                    checked={formData.quorum_verified_manually}
                    onChange={(e) => handleChange('quorum_verified_manually', e.target.checked)}
                    color="primary"
                  />
                }
                label="I verify that the meeting quorum was met"
              />
              {formData.quorum_verified_manually && (
                <TextField
                  fullWidth
                  multiline
                  rows={2}
                  label="Quorum Verification Notes"
                  value={formData.quorum_verification_notes}
                  onChange={(e) => handleChange('quorum_verification_notes', e.target.value)}
                  placeholder="Add any notes about quorum verification"
                  sx={{ mt: 2 }}
                />
              )}
            </Grid>

            {/* Criterion 3: Manual Meeting Attendance Verification */}
            <Grid item xs={12}>
              <Alert severity="info" sx={{ mb: 2 }}>
                <Typography variant="subtitle2" gutterBottom>
                  Criterion 3: Meeting Attendance
                </Typography>
                <Typography variant="body2">
                  Confirm that the required meeting actually took place with proper attendance.
                </Typography>
              </Alert>
              <FormControlLabel
                control={
                  <Checkbox
                    checked={formData.meeting_took_place_verified}
                    onChange={(e) => handleChange('meeting_took_place_verified', e.target.checked)}
                    color="primary"
                  />
                }
                label="I confirm that the meeting took place as recorded"
              />
              {formData.meeting_took_place_verified && (
                <TextField
                  fullWidth
                  multiline
                  rows={2}
                  label="Meeting Verification Notes"
                  value={formData.meeting_verification_notes}
                  onChange={(e) => handleChange('meeting_verification_notes', e.target.value)}
                  placeholder="Add any notes about meeting attendance"
                  sx={{ mt: 2 }}
                />
              )}
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenDialog(false)}>Cancel</Button>
          <Button 
            onClick={handleSubmit} 
            variant="contained"
            disabled={createMeetingMutation.isPending}
          >
            {createMeetingMutation.isPending ? 'Saving...' : 'Save Meeting'}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default WardMeetingManagement;

